import time
from pathlib import Path
from typing import List, Dict, Any, Optional
from jinja2 import Template
from fpdf import FPDF

from stock_tracker.config import settings
from stock_tracker.core.data_fetcher import fetcher
from stock_tracker.core.technical_analysis import ta_engine
from stock_tracker.core.alert_engine import alert_engine

HTML_REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Daily Stock Market Analysis Report</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #0f172a; color: #f8fafc; margin: 0; padding: 20px; }
        .container { max-width: 900px; margin: 0 auto; background: #1e293b; border-radius: 12px; padding: 24px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }
        h1 { color: #38bdf8; border-bottom: 2px solid #334155; padding-bottom: 10px; margin-top: 0; }
        .subtitle { color: #94a3b8; font-size: 14px; margin-bottom: 24px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th { background: #334155; color: #e2e8f0; text-align: left; padding: 12px; font-size: 14px; }
        td { padding: 12px; border-bottom: 1px solid #334155; font-size: 14px; }
        tr:hover { background-color: #243447; }
        .green { color: #4ade80; font-weight: bold; }
        .red { color: #f87171; font-weight: bold; }
        .badge { background: #334155; padding: 4px 8px; border-radius: 4px; font-size: 12px; }
        .summary-card { background: #0f172a; padding: 16px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #38bdf8; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #64748b; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Stock Market Analysis Report</h1>
        <div class="subtitle">Generated on {{ report_time }} | Market Watchlist Summary</div>
        
        <div class="summary-card">
            <strong>Market Overview:</strong> Tracking {{ total_stocks }} securities. 
            <span class="green">{{ gainers }} Gainers</span> | 
            <span class="red">{{ losers }} Losers</span>
        </div>

        <h2>Watchlist Summary Table</h2>
        <table>
            <thead>
                <tr>
                    <th>Ticker</th>
                    <th>Price</th>
                    <th>Change</th>
                    <th>Change %</th>
                    <th>Volume</th>
                    <th>Market Cap</th>
                    <th>52-Week Range</th>
                    <th>Trend Bias</th>
                </tr>
            </thead>
            <tbody>
                {% for stock in stocks %}
                <tr>
                    <td><strong>{{ stock.ticker }}</strong><br><small style="color:#94a3b8">{{ stock.name }}</small></td>
                    <td>${{ "%.2f"|format(stock.price) }}</td>
                    <td class="{{ 'green' if stock.change >= 0 else 'red' }}">
                        {{ "+%.2f"|format(stock.change) if stock.change >= 0 else "%.2f"|format(stock.change) }}
                    </td>
                    <td class="{{ 'green' if stock.change_percent >= 0 else 'red' }}">
                        {{ "+%.2f%%"|format(stock.change_percent) if stock.change_percent >= 0 else "%.2f%%"|format(stock.change_percent) }}
                    </td>
                    <td>{{ stock.volume_str }}</td>
                    <td>{{ stock.market_cap_str }}</td>
                    <td>${{ stock.fifty_two_week_low }} - ${{ stock.fifty_two_week_high }}</td>
                    <td><span class="badge">{{ stock.ta.overall_trend }}</span></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h2>Technical Indicators Detail</h2>
        <table>
            <thead>
                <tr>
                    <th>Ticker</th>
                    <th>RSI (14)</th>
                    <th>RSI Signal</th>
                    <th>MACD</th>
                    <th>MACD Signal</th>
                    <th>SMA 20</th>
                    <th>SMA 50</th>
                </tr>
            </thead>
            <tbody>
                {% for stock in stocks %}
                <tr>
                    <td><strong>{{ stock.ticker }}</strong></td>
                    <td>{{ stock.ta.rsi if stock.ta.rsi else 'N/A' }}</td>
                    <td>{{ stock.ta.rsi_status }}</td>
                    <td>{{ stock.ta.macd if stock.ta.macd else 'N/A' }}</td>
                    <td>{{ stock.ta.macd_status }}</td>
                    <td>${{ stock.ta.sma_20 if stock.ta.sma_20 else 'N/A' }}</td>
                    <td>${{ stock.ta.sma_50 if stock.ta.sma_50 else 'N/A' }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="footer">
            Report generated by {{ app_name }} v{{ app_version }}
        </div>
    </div>
</body>
</html>
"""

class StockPDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 14)
        self.set_text_color(30, 41, 59)
        self.cell(0, 8, 'Stock Market Analysis Report', 0, 1, 'L')
        self.set_draw_color(56, 189, 248)
        self.set_line_width(0.8)
        self.line(10, 18, 200, 18)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(100, 116, 139)
        self.cell(0, 10, f'Generated by {settings.APP_NAME} - Page {self.page_no()}', 0, 0, 'C')

class ReportGenerator:
    """Generates styled HTML, PDF, plain text, and email reports."""

    @staticmethod
    def create_pdf_report(report_time: str, stocks_data: List[Dict[str, Any]], pdf_path: Path):
        """Builds a formatted PDF document using FPDF."""
        pdf = StockPDFReport()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Date Subtitle
        pdf.set_font('Arial', 'I', 9)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 6, f'Generated: {report_time} | Market Watchlist Summary', 0, 1, 'L')
        pdf.ln(4)

        # Overview Table
        pdf.set_font('Arial', 'B', 11)
        pdf.set_fill_color(241, 245, 249)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 8, ' Watchlist Summary', 0, 1, 'L', fill=True)
        pdf.ln(2)

        # Header Row
        pdf.set_font('Arial', 'B', 8)
        pdf.set_fill_color(30, 41, 59)
        pdf.set_text_color(255, 255, 255)
        
        # Column widths: Ticker(18), Price(22), Change(22), Change%(22), Vol(22), MktCap(24), 52w(35), Trend(25)
        pdf.cell(18, 7, 'Ticker', 1, 0, 'C', fill=True)
        pdf.cell(22, 7, 'Price', 1, 0, 'R', fill=True)
        pdf.cell(22, 7, 'Change', 1, 0, 'R', fill=True)
        pdf.cell(22, 7, 'Change %', 1, 0, 'R', fill=True)
        pdf.cell(22, 7, 'Volume', 1, 0, 'R', fill=True)
        pdf.cell(24, 7, 'Market Cap', 1, 0, 'R', fill=True)
        pdf.cell(35, 7, '52-Wk Range', 1, 0, 'C', fill=True)
        pdf.cell(25, 7, 'Trend', 1, 1, 'C', fill=True)

        # Data Rows
        pdf.set_font('Arial', '', 8)
        for s in stocks_data:
            pdf.set_text_color(15, 23, 42)
            pdf.cell(18, 6, s['ticker'], 1, 0, 'C')
            pdf.cell(22, 6, f"${s['price']:.2f}", 1, 0, 'R')
            
            # Color change
            chg = s['change']
            if chg >= 0:
                pdf.set_text_color(34, 197, 94) # Green
                chg_str = f"+${chg:.2f}"
                chg_pct = f"+{s['change_percent']:.2f}%"
            else:
                pdf.set_text_color(239, 68, 68) # Red
                chg_str = f"-${abs(chg):.2f}"
                chg_pct = f"{s['change_percent']:.2f}%"
                
            pdf.cell(22, 6, chg_str, 1, 0, 'R')
            pdf.cell(22, 6, chg_pct, 1, 0, 'R')
            
            pdf.set_text_color(15, 23, 42)
            pdf.cell(22, 6, s['volume_str'], 1, 0, 'R')
            pdf.cell(24, 6, s['market_cap_str'], 1, 0, 'R')
            pdf.cell(35, 6, f"${s['fifty_two_week_low']} - ${s['fifty_two_week_high']}", 1, 0, 'C')
            pdf.cell(25, 6, s['ta'].get('overall_trend', 'N/A'), 1, 1, 'C')

        pdf.ln(6)

        # Technical Indicators Section
        pdf.set_font('Arial', 'B', 11)
        pdf.set_fill_color(241, 245, 249)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 8, ' Technical Analysis & Indicators', 0, 1, 'L', fill=True)
        pdf.ln(2)

        # Header Row Technicals
        pdf.set_font('Arial', 'B', 8)
        pdf.set_fill_color(30, 41, 59)
        pdf.set_text_color(255, 255, 255)
        
        pdf.cell(20, 7, 'Ticker', 1, 0, 'C', fill=True)
        pdf.cell(20, 7, 'RSI (14)', 1, 0, 'C', fill=True)
        pdf.cell(45, 7, 'RSI Signal', 1, 0, 'L', fill=True)
        pdf.cell(25, 7, 'MACD', 1, 0, 'R', fill=True)
        pdf.cell(45, 7, 'MACD Signal', 1, 0, 'L', fill=True)
        pdf.cell(35, 7, 'SMA 20 / SMA 50', 1, 1, 'C', fill=True)

        pdf.set_font('Arial', '', 8)
        pdf.set_text_color(15, 23, 42)
        for s in stocks_data:
            ta = s.get('ta', {})
            rsi = str(ta.get('rsi')) if ta.get('rsi') else 'N/A'
            macd = str(ta.get('macd')) if ta.get('macd') else 'N/A'
            sma20 = f"${ta['sma_20']}" if ta.get('sma_20') else 'N/A'
            sma50 = f"${ta['sma_50']}" if ta.get('sma_50') else 'N/A'

            pdf.cell(20, 6, s['ticker'], 1, 0, 'C')
            pdf.cell(20, 6, rsi, 1, 0, 'C')
            pdf.cell(45, 6, ta.get('rsi_status', 'N/A'), 1, 0, 'L')
            pdf.cell(25, 6, macd, 1, 0, 'R')
            pdf.cell(45, 6, ta.get('macd_status', 'N/A'), 1, 0, 'L')
            pdf.cell(35, 6, f"{sma20} / {sma50}", 1, 1, 'C')

        pdf.output(str(pdf_path))

    @classmethod
    def generate_report(cls, tickers: List[str]) -> Dict[str, Any]:
        """Collects metrics for all tickers and constructs HTML, PDF & Text report files."""
        stocks_data = []
        gainers = 0
        losers = 0

        for ticker in tickers:
            quote = fetcher.get_stock_quote(ticker)
            df = fetcher.get_historical_data(ticker, period="6mo")
            ta = ta_engine.get_analysis_summary(df)
            
            quote["ta"] = ta
            stocks_data.append(quote)

            if quote.get("change", 0) >= 0:
                gainers += 1
            else:
                losers += 1

        report_time = time.strftime("%Y-%m-%d %H:%M:%S")
        timestamp_slug = time.strftime("%Y%m%d_%H%M%S")

        # Render HTML
        template = Template(HTML_REPORT_TEMPLATE)
        html_content = template.render(
            report_time=report_time,
            total_stocks=len(tickers),
            gainers=gainers,
            losers=losers,
            stocks=stocks_data,
            app_name=settings.APP_NAME,
            app_version=settings.VERSION
        )

        # Build Plain Text Version
        lines = []
        lines.append("==========================================================")
        lines.append(f"  {settings.APP_NAME} - Stock Report")
        lines.append(f"  Generated: {report_time}")
        lines.append("==========================================================")
        lines.append(f"Tracked Stocks: {len(tickers)} | Gainers: {gainers} | Losers: {losers}")
        lines.append("-" * 58)
        lines.append(f"{'Ticker':<8} {'Price':<10} {'Change':<10} {'Change%':<10} {'Volume':<8}")
        lines.append("-" * 58)
        for s in stocks_data:
            chg = f"{s['change']:+.2f}"
            chg_pct = f"{s['change_percent']:+.2f}%"
            lines.append(f"{s['ticker']:<8} ${s['price']:<9.2f} {chg:<10} {chg_pct:<10} {s['volume_str']:<8}")
        lines.append("==========================================================")
        text_content = "\n".join(lines)

        # Save HTML file
        html_filename = f"report_{timestamp_slug}.html"
        html_file = settings.REPORTS_DIR / html_filename
        with open(html_file, "w", encoding="utf-8") as f:
            f.write(html_content)

        # Save PDF file
        pdf_filename = f"report_{timestamp_slug}.pdf"
        pdf_file = settings.REPORTS_DIR / pdf_filename
        cls.create_pdf_report(report_time, stocks_data, pdf_file)

        return {
            "report_time": report_time,
            "html_filename": html_filename,
            "html_filepath": str(html_file),
            "pdf_filename": pdf_filename,
            "pdf_filepath": str(pdf_file),
            "html": html_content,
            "text": text_content,
            "stocks": stocks_data
        }

    @classmethod
    def generate_and_email_report(cls, tickers: List[str], recipient: Optional[str] = None) -> bool:
        """Generates report and emails it to the specified or configured address."""
        res = cls.generate_report(tickers)
        subject = f"Daily Stock Market Report - {res['report_time']}"
        return alert_engine.send_email_notification(
            subject=subject,
            body_text=res["text"],
            body_html=res["html"],
            recipient=recipient
        )

report_gen = ReportGenerator()
